development:
  basedir: files/documents
  public_host_root_url: http://localhost

test:
  basedir: spec/tmp/files/documents
  public_host_root_url: http://localhost

staging:
  basedir: files/documents
  public_host_root_url: http://localhost

production:
  basedir: files/documents
  public_host_root_url: http://localhost
