development:
  basedir: public
  public_host_root_url: http://localhost:3000

test:
  basedir: spec/tmp/files/documents
  public_host_root_url: http://localhost:3000

staging:
  basedir: public
  public_host_root_url: http://localhost:3000

production:
  basedir: public
  public_host_root_url: http://localhost:3000
