package_assets: on
compress_assets: on
javascript_compressor: yui
stylesheets:
  common:
    - public/stylesheets/reset.css
    - public/stylesheets/jquery-ui-1.8rc3.custom.css
    - public/stylesheets/lib/states.css
    - public/stylesheets/lib/forms.css
    - public/stylesheets/lib/index.css
    - public/stylesheets/lib/layer.css
    - public/stylesheets/lib/column.css
    - public/stylesheets/style.css
    - public/stylesheets/style.ui.css
  document_editor:
    - public/stylesheets/style.application.css
    - public/stylesheets/style.application.color.css
    - public/stylesheets/style.application.typography.css
  application:
    - public/stylesheets/style.application.css
    - public/stylesheets/style.application.color.css
    - public/stylesheets/style.application.typography.css
    - public/stylesheets/formtastic.css   
    - public/stylesheets/formtastic_changes.css 
  page_editor:    
    - public/stylesheets/library.css
    - public/stylesheets/lib/protect.css
    - public/stylesheets/lib/panel.css
    - public/stylesheets/style.editor.css    
    - public/stylesheets/style.editor.colors.css
    - public/stylesheets/colorpicker.css
    - public/stylesheets/toolbar.css
      
javascripts:
  common:
    - public/javascripts/jquery-1.4.2.js
    - public/javascripts/jquery-json.js
    - public/javascripts/jquery-string.js
    - public/javascripts/jquery.extensions.js
    - public/javascripts/jquery.events.js
    - public/javascripts/jquery.panel.js
    - public/javascripts/jquery.pop.js
    - public/javascripts/klass.js    
    - public/swfupload/swfupload.js
    - public/javascripts/jquery-swfupload.js
    - public/javscripts/jquery.form.js
    - public/javascripts/jquery.hashchange.js
    - public/javascripts/colorpicker.js
    - public/javascripts/jquery-ui-1.8.js
  mtools:
    - app/javascripts/mtools.js
    - app/javascripts/mtools/*.js
  document_editor:
    - app/javascripts/webdoc.js
    - app/javascripts/webdoc/model/*.js
    - app/javascripts/webdoc/utils/*.js
    - app/javascripts/webdoc/controllers/document_access_controller.js
    - app/javascripts/webdoc/controllers/document_categories_controller.js
    - app/javascripts/webdoc/controllers/document_share_controller.js
    - app/javascripts/webdoc/gui/document_list.js
    - app/javascripts/webdoc/core/document_editor.js
  page_editor:
    - public/javascripts/sylvester.js
    - public/javascripts/strophe.js
    - public/javascripts/codemirror/codemirror.js
    - app/javascripts/webdoc.js
    - app/javascripts/webdoc/model/*.js
    - app/javascripts/webdoc/sdk/*.js
    - app/javascripts/webdoc/adaptors/*.js
    - app/javascripts/webdoc/utils/*.js
    - app/javascripts/webdoc/gui/item_view.js
    - app/javascripts/webdoc/gui/drawing_view.js
    - app/javascripts/webdoc/gui/image_view.js
    - app/javascripts/webdoc/gui/item_thumbnail_view.js
    - app/javascripts/webdoc/gui/page_browser_item_view.js
    - app/javascripts/webdoc/gui/page_thumbnail_view.js
    - app/javascripts/webdoc/gui/page_view.js
    - app/javascripts/webdoc/gui/text_view.js
    - app/javascripts/webdoc/gui/widget_view.js
    - app/javascripts/webdoc/tools/tool.js
    - app/javascripts/webdoc/tools/arrow_tool.js
    - app/javascripts/webdoc/tools/drawing_tool.js
    - app/javascripts/webdoc/tools/hand_tool.js
    - app/javascripts/webdoc/tools/html_tool.js
    - app/javascripts/webdoc/tools/text_tool.js
    - app/javascripts/webdoc/tools/text_tool/*.js
    - app/javascripts/webdoc/controllers/*.js  
    - app/javascripts/webdoc/controllers/inspectors/*.js
    - app/javascripts/webdoc/core/*.js
    - app/javascripts/webdoc/library/jqtouch.js
    - app/javascripts/webdoc/library/libraries_controller.js
    - app/javascripts/webdoc/library/apps_library.js
    - app/javascripts/webdoc/library/images_library/*.js
    - app/javascripts/webdoc/library/images_library.js
    - app/javascripts/webdoc/library/videos_library/*.js
    - app/javascripts/webdoc/library/videos_library.js
    - app/javascripts/webdoc/library/web_browser.js
  tests:
    - app/javascripts/tests/mtools/*.js
          