package_assets: on
compress_assets: on
javascript_compressor: yui
stylesheets:
  common:
    - public/css/webcss/reset.css
    - public/css/webcss/forms.css
    - public/css/webcss/states.css
    - public/css/webcss/layout.css
    - public/css/webcss/wrap.css
    - public/css/webcss/index.css
    - public/css/webcss/layer.css
    - public/css/webcss/layout.css
    - public/css/webcss/panel.css
    - public/css/webcss/column.css
    - public/css/webcss/card.css
    - public/css/webcss/button.css
    - public/css/webcss/thumb.css
    - public/css/webcss/scrollbar.css
    - public/css/webcss/message.css
    
    - public/css/webdoc/site.layout.css
    - public/css/webdoc/site.color.css
    - public/css/webdoc/site.typography.css
    
    - public/css/webdoc/flash.css
    - public/css/jquery-ui/jquery-ui-1.8.css
  home:
    - public/css/webdoc/home.layout.css
    - public/css/webdoc/home.color.css
  account:
    - public/css/webdoc/account.layout.css
    - public/css/webdoc/account.color.css
  dashboard:
    - public/css/webdoc/dashboard.layout.css
    - public/css/webdoc/dashboard.color.css
  editor:
    - public/css/webdoc/editor.color.css
    - public/css/webdoc/editor.layout.css
    - public/css/webdoc/editor.typography.css
    
    - public/css/webdoc/panel.color.css
    - public/css/webdoc/panel.layout.css
    - public/css/webdoc/panel.typography.css
    
    - public/css/webdoc/webdoc.color.css
    - public/css/webdoc/webdoc.layout.css
    - public/css/webdoc/webdoc.typography.css
    
    - public/css/webdoc/inspector.color.css
    - public/css/webdoc/inspector.layout.css
    - public/css/webdoc/inspector.typography.css
    
    - public/css/webdoc/comment.layout.css
    
    - public/css/webdoc/item.css
    - public/css/colorpicker/colorpicker.css
    - public/css/text-tool/toolbar.css
    - public/css/codemirror/codemirror.css
  profile:
    - public/css/webdoc/profile.layout.css
    - public/css/webdoc/profile.color.css
  friends:
    - public/css/webdoc/friends.layout.css
    - public/css/webdoc/friends.color.css
  explore:
    - public/css/webdoc/explore.layout.css
    - public/css/webdoc/explore.color.css
  
#  fonts:
#    - public/fonts/Aaargh-fontfacekit/stylesheet
#    - public/fonts/Adler-fontfacekit/stylesheet
#    - public/fonts/CalligraphyFLF-fontfacekit/stylesheet
#    - public/fonts/Colaborate-fontfacekit/stylesheet
#    - public/fonts/Creampuff-fontfacekit/stylesheet
#    - public/fonts/Droid-Sans-fontfacekit/stylesheet
#    - public/fonts/ElliotSix-fontfacekit/stylesheet
#    - public/fonts/GoodDog-fontfacekit/stylesheet
#    - public/fonts/Impact-Label-fontfacekit/stylesheet
#    - public/fonts/Inconsolata-fontfacekit/stylesheet
#    - public/fonts/JungleFever-fontfacekit/stylesheet
#    - public/fonts/Komika-Title-fontfacekit/stylesheet
#    - public/fonts/League-Gothic-fontfacekit/stylesheet
#    - public/fonts/Mirisch-fontfacekit/stylesheet
#    - public/fonts/MomsTypewriter-fontfacekit/stylesheet
#    - public/fonts/MonospaceTypewriter-fontfacekit/stylesheet
#    - public/fonts/Playtime-With-Hot-Toddies-fontfacekit/stylesheet
#    - public/fonts/SF-Cartoonist-Hand-fontfacekit/stylesheet
#    - public/fonts/Shardee-fontfacekit/stylesheet
#    - public/fonts/Underwood-Champion-fontfacekit/stylesheet
  
  feedback:
    - public/css/zenbox/zenbox.css
  
javascripts:
  common:
    - public/js/jquery-1.4.2.js
    - public/js/rails.js
    - public/js/jquery-json.js
    - public/js/jquery-string.js
    - public/js/jquery.form.js
    - public/js/jquery.extensions.js
    - public/js/jquery.events.js
    - public/js/jquery.list.js
    - public/js/jquery.pop.js
    - public/js/jquery.truncate.js
    - public/js/jquery.validator.js
    - public/js/jquery.flash.js
    - public/js/jquery.cuteTime.min.js
    - public/js/jquery.scrollbars.js
    - public/js/jquery.cookie.js
    - public/js/klass.js
    - public/swfupload/swfupload.js
    - public/js/jquery-swfupload.js
    - public/js/jquery.hashchange.js
    - public/js/colorpicker.js
    - public/js/jquery-ui-1.8.2.js
    - public/js/editor.ui.js
    - app/javascripts/webdoc.js
    - app/javascripts/webdoc/common/*.js
    - app/javascripts/webdoc/model/*.js
    - app/javascripts/webdoc/card/card.js

  document_editor:
    - app/javascripts/webdoc/utils/*.js
    - app/javascripts/webdoc/managers/*
    - app/javascripts/webdoc/controllers/friends_selector_controller.js
    - app/javascripts/webdoc/controllers/email_invitation_controller.js
    - app/javascripts/webdoc/controllers/document_collaboration_controller.js
    - app/javascripts/webdoc/controllers/document_share_controller.js
    - app/javascripts/webdoc/controllers/invitations_controller.js
    - app/javascripts/webdoc/gui/document_list.js
    - app/javascripts/webdoc/core/document_editor.js
  editor:
    - public/js/sylvester.js
    - public/js/strophe.js
    - public/js/jquery.svg.js
    
    # code highlighting
    - public/codemirror/js/codemirror.js
    - public/codemirror/js/highlight.js
    - public/codemirror/js/stringstream.js
    - public/codemirror/js/tokenize.js
    - public/codemirror/js/tokenizejavascript.js
    - public/codemirror/js/parsecss.js
    - public/codemirror/js/parsexml.js
    - public/codemirror/js/parsejavascript.js
    - public/codemirror/js/parsehtmlmixed.js
    
    - app/javascripts/webdoc/managers/*
    - app/javascripts/webdoc/sdk/*.js
    - app/javascripts/webdoc/adaptors/*.js
    - app/javascripts/webdoc/utils/*.js
    - app/javascripts/webdoc/gui/inspector_pane_view.js
    - app/javascripts/webdoc/gui/item_view.js
    - app/javascripts/webdoc/gui/drawing_view.js
    - app/javascripts/webdoc/gui/image_view.js
    - app/javascripts/webdoc/gui/item_thumbnail_view.js
    - app/javascripts/webdoc/gui/page_browser_item_view.js
    - app/javascripts/webdoc/gui/page_thumbnail_view.js
    - app/javascripts/webdoc/gui/page_view.js
    - app/javascripts/webdoc/gui/text_view.js
    - app/javascripts/webdoc/gui/textbox_view.js
    - app/javascripts/webdoc/gui/widget_view.js
    - app/javascripts/webdoc/gui/html_view.js
    - app/javascripts/webdoc/gui/iframe_view.js
    - app/javascripts/webdoc/gui/app_view.js
    - app/javascripts/webdoc/gui/discussion_view.js
    - app/javascripts/webdoc/tools/tool.js
    - app/javascripts/webdoc/tools/arrow_tool.js
    - app/javascripts/webdoc/tools/browser_tool.js
    - app/javascripts/webdoc/tools/drawing_tool.js
    - app/javascripts/webdoc/tools/hand_tool.js
    - app/javascripts/webdoc/tools/html_tool.js
    - app/javascripts/webdoc/tools/iframe_tool.js
    - app/javascripts/webdoc/tools/app_tool.js
    - app/javascripts/webdoc/tools/text_tool.js
    - app/javascripts/webdoc/tools/textbox_tool.js
    - app/javascripts/webdoc/tools/text_tool/*.js
    - app/javascripts/webdoc/controllers/*.js  
    - app/javascripts/webdoc/controllers/panel_controllers/*.js
    - app/javascripts/webdoc/controllers/inspectors/*.js
    - app/javascripts/webdoc/core/*.js
    
    - app/javascripts/webdoc/media_browser/library.js
    - app/javascripts/webdoc/media_browser/apps_library.js
    - app/javascripts/webdoc/media_browser/images_uploader.js
    - app/javascripts/webdoc/media_browser/sha1.js
    - app/javascripts/webdoc/media_browser/web_images_search.js
    - app/javascripts/webdoc/media_browser/web_videos_search.js
    - app/javascripts/webdoc/media_browser/images_uploader.js
    - app/javascripts/webdoc/media_browser/theme_elements_library.js
    - app/javascripts/webdoc/media_browser/packages_library.js
    - app/javascripts/webdoc/media_browser/web_browser.js
    - app/javascripts/webdoc/media_browser/web_search_controller.js
    - app/javascripts/webdoc/media_browser/my_contents_controller.js
    - app/javascripts/webdoc/media_browser/media_browser_controller.js
    
    - app/javascripts/webdoc/controllers/friends_selector_controller.js
    - app/javascripts/webdoc/controllers/email_invitation_controller.js
    - app/javascripts/webdoc/controllers/document_collaboration_controller.js
    - app/javascripts/webdoc/controllers/document_share_controller.js
    - app/javascripts/webdoc/controllers/invitations_controller.js
    - app/javascripts/webdoc/gui/document_list.js
    - app/javascripts/webdoc/core/document_editor.js
  explore:
    - app/javascripts/webdoc/explore/*.js
  tests:
    - app/javascripts/tests/test_helper.js
    - app/javascripts/tests/mtools/*.js
  forms:
    - app/javascripts/webdoc/form/*.js
  contacts:
    - app/javascripts/webdoc/card/*.js
  apps:
    - app/javascripts/webdoc/apps/apps_messaging.js
    - app/javascripts/webdoc/apps/apps.js
  feedback:
    - app/javascripts/webdoc/feedback/zendesk.js
  static_page:
    - app/javascripts/webdoc/explore/webdoc_viewer.js
    - app/javascripts/webdoc/core/static_page.js
