package_assets: on
compress_assets: on
javascript_compressor: yui
stylesheets:
  common:
    - public/stylesheets/reset.css
    - public/stylesheets/jquery-ui-1.8rc3.custom.css
    - public/stylesheets/lib/states.css
    - public/stylesheets/lib/forms.css
    - public/stylesheets/lib/index.css
    - public/stylesheets/lib/layer.css
    - public/stylesheets/lib/column.css
    - public/stylesheets/lib/card.css
    - public/stylesheets/style.css
    - public/stylesheets/style.ui.css

  application:
    - public/stylesheets/style.application.css
    - public/stylesheets/style.application.typography.css
    - public/stylesheets/style.application.color.css

  page_editor:    
    - public/stylesheets/library.css
    - public/stylesheets/lib/panel.css
    - public/stylesheets/lib/protect.css    
    - public/stylesheets/style.editor.css
    - public/stylesheets/style.editor.colors.css
    - public/stylesheets/style.editor.apps.inspector.outer.css
    - public/stylesheets/style.webdoc.css
    - public/stylesheets/colorpicker.css
    - public/stylesheets/toolbar.css
    
    # code highlighting
    - public/stylesheets/style.codemirror.css
  
#  font_collection:
#    - public/fonts/Aaargh-fontfacekit/stylesheet
#    - public/fonts/Adler-fontfacekit/stylesheet
#    - public/fonts/CalligraphyFLF-fontfacekit/stylesheet
#    - public/fonts/Colaborate-fontfacekit/stylesheet
#    - public/fonts/Creampuff-fontfacekit/stylesheet
#    - public/fonts/Droid-Sans-fontfacekit/stylesheet
#    - public/fonts/ElliotSix-fontfacekit/stylesheet
#    - public/fonts/GoodDog-fontfacekit/stylesheet
#    - public/fonts/Impact-Label-fontfacekit/stylesheet
#    - public/fonts/Inconsolata-fontfacekit/stylesheet
#    - public/fonts/JungleFever-fontfacekit/stylesheet
#    - public/fonts/Komika-Title-fontfacekit/stylesheet
#    - public/fonts/League-Gothic-fontfacekit/stylesheet
#    - public/fonts/Mirisch-fontfacekit/stylesheet
#    - public/fonts/MomsTypewriter-fontfacekit/stylesheet
#    - public/fonts/MonospaceTypewriter-fontfacekit/stylesheet
#    - public/fonts/Playtime-With-Hot-Toddies-fontfacekit/stylesheet
#    - public/fonts/SF-Cartoonist-Hand-fontfacekit/stylesheet
#    - public/fonts/Shardee-fontfacekit/stylesheet
#    - public/fonts/Underwood-Champion-fontfacekit/stylesheet
    
  page_viewer:
    - public/stylesheets/style.webdoc.css
  
  feedback:
    - public/stylesheets/zenbox.css
  
javascripts:
  common:
    - public/javascripts/jquery-1.4.2.js
    - public/javascripts/jquery-json.js
    - public/javascripts/jquery-string.js
    - public/javascripts/jquery.form.js
    - public/javascripts/jquery.extensions.js
    - public/javascripts/jquery.events.js
    - public/javascripts/jquery.list.js
    - public/javascripts/jquery.pop.js
    - public/javascripts/jquery.truncate.js
    - public/javascripts/jquery.validator.js
    - public/javascripts/jquery.flash.js
    - public/javascripts/jquery.cookie.js
    - public/javascripts/klass.js    
    - public/swfupload/swfupload.js
    - public/javascripts/jquery-swfupload.js
    - public/javascripts/jquery.hashchange.js
    - public/javascripts/colorpicker.js
    - public/javascripts/jquery-ui-1.8.js
    - app/javascripts/webdoc.js
    - app/javascripts/webdoc/common/*.js
    - app/javascripts/webdoc/model/*.js

  document_editor:
    - app/javascripts/webdoc/utils/*.js
    - app/javascripts/webdoc/managers/*
    - app/javascripts/webdoc/controllers/document_collaboration_controller.js
    - app/javascripts/webdoc/controllers/document_share_controller.js
    - app/javascripts/webdoc/gui/document_list.js
    - app/javascripts/webdoc/core/document_editor.js
  page_editor:
    - public/javascripts/sylvester.js
    - public/javascripts/strophe.js
    
    # code highlighting
    - public/codemirror/js/codemirror.js
    - public/codemirror/js/highlight.js
    - public/codemirror/js/stringstream.js
    - public/codemirror/js/tokenize.js
    - public/codemirror/js/tokenizejavascript.js
    - public/codemirror/js/parsecss.js
    - public/codemirror/js/parsexml.js
    - public/codemirror/js/parsejavascript.js
    - public/codemirror/js/parsehtmlmixed.js
    
    - app/javascripts/webdoc/managers/*
    - app/javascripts/webdoc/sdk/*.js
    - app/javascripts/webdoc/adaptors/*.js
    - app/javascripts/webdoc/utils/*.js
    - app/javascripts/webdoc/gui/inspector_pane_view.js
    - app/javascripts/webdoc/gui/item_view.js
    - app/javascripts/webdoc/gui/drawing_view.js
    - app/javascripts/webdoc/gui/image_view.js
    - app/javascripts/webdoc/gui/item_thumbnail_view.js
    - app/javascripts/webdoc/gui/page_browser_item_view.js
    - app/javascripts/webdoc/gui/page_thumbnail_view.js
    - app/javascripts/webdoc/gui/page_view.js
    - app/javascripts/webdoc/gui/text_view.js
    - app/javascripts/webdoc/gui/widget_view.js
    - app/javascripts/webdoc/gui/html_view.js
    - app/javascripts/webdoc/gui/iframe_view.js
    - app/javascripts/webdoc/gui/app_view.js
    - app/javascripts/webdoc/tools/tool.js
    - app/javascripts/webdoc/tools/arrow_tool.js
    - app/javascripts/webdoc/tools/browser_tool.js
    - app/javascripts/webdoc/tools/drawing_tool.js
    - app/javascripts/webdoc/tools/hand_tool.js
    - app/javascripts/webdoc/tools/html_tool.js
    - app/javascripts/webdoc/tools/iframe_tool.js
    - app/javascripts/webdoc/tools/app_tool.js
    - app/javascripts/webdoc/tools/text_tool.js
    - app/javascripts/webdoc/tools/text_tool/*.js
    - app/javascripts/webdoc/controllers/*.js  
    - app/javascripts/webdoc/controllers/right_bar_controllers/*.js
    - app/javascripts/webdoc/controllers/inspectors/*.js
    - app/javascripts/webdoc/core/*.js
    
    - app/javascripts/webdoc/media_browser/media_browser_controller.js
    
    - app/javascripts/webdoc/library/jqtouch.js
    - app/javascripts/webdoc/library/libraries_controller.js
    - app/javascripts/webdoc/library/apps_library.js
    - app/javascripts/webdoc/library/images_library/*.js
    - app/javascripts/webdoc/library/images_library.js
    - app/javascripts/webdoc/library/videos_library/*.js
    - app/javascripts/webdoc/library/videos_library.js
    - app/javascripts/webdoc/library/theme_elements_library.js
    - app/javascripts/webdoc/library/web_browser.js
    - app/javascripts/webdoc/card/card.js
  explore:
    - app/javascripts/webdoc/explore/*.js
  tests:
    - app/javascripts/tests/test_helper.js
    - app/javascripts/tests/mtools/*.js
  forms:
    - app/javascripts/webdoc/form/*.js
  contacts:
    - app/javascripts/webdoc/card/*.js
  apps:
    - app/javascripts/webdoc/apps/apps_messaging.js
    - app/javascripts/webdoc/apps/apps.js
  feedback:
    - app/javascripts/webdoc/feedback/zendesk.js