package_assets: on
compress_assets: on
javascript_compressor: yui
javascripts:
  mtools:
    - app/javascripts/mtools.js
    - app/javascripts/mtools/*.js
  document_editor:
    - app/javascripts/webdoc.js
    - app/javascripts/webdoc/model/*.js
    - app/javascripts/webdoc/utils/*.js
    - app/javascripts/webdoc/controllers/document_access_controller.js
    - app/javascripts/webdoc/controllers/document_categories_controller.js
    - app/javascripts/webdoc/controllers/document_share_controller.js
    - app/javascripts/webdoc/gui/document_list.js
    - app/javascripts/webdoc/core/document_editor.js
  page_editor:
    - app/javascripts/webdoc.js
    - app/javascripts/webdoc/model/*.js
    - app/javascripts/webdoc/sdk/*.js
    - app/javascripts/webdoc/adaptors/*.js
    - app/javascripts/webdoc/utils/*.js
    - app/javascripts/webdoc/gui/item_view.js
    - app/javascripts/webdoc/gui/drawing_view.js
    - app/javascripts/webdoc/gui/image_view.js
    - app/javascripts/webdoc/gui/item_thumbnail_view.js
    - app/javascripts/webdoc/gui/page_browser_item_view.js
    - app/javascripts/webdoc/gui/page_thumbnail_view.js
    - app/javascripts/webdoc/gui/page_view.js
    - app/javascripts/webdoc/gui/text_view.js
    - app/javascripts/webdoc/gui/widget_view.js
    - app/javascripts/webdoc/tools/tool.js
    - app/javascripts/webdoc/tools/arrow_tool.js
    - app/javascripts/webdoc/tools/drawing_tool.js
    - app/javascripts/webdoc/tools/hand_tool.js
    - app/javascripts/webdoc/tools/html_tool.js
    - app/javascripts/webdoc/tools/text_tool.js
    - app/javascripts/webdoc/tools/text_tool/*.js
    - app/javascripts/webdoc/controllers/*.js  
    - app/javascripts/webdoc/controllers/inspectors/*.js
    - app/javascripts/webdoc/core/*.js

    - app/javascripts/webdoc/library/jqtouch.js
    - app/javascripts/webdoc/library/libraries_controller.js
    - app/javascripts/webdoc/library/apps_library.js
    - app/javascripts/webdoc/library/images_library/*.js
    - app/javascripts/webdoc/library/images_library.js
    - app/javascripts/webdoc/library/videos_library/*.js
    - app/javascripts/webdoc/library/videos_library.js
    - app/javascripts/webdoc/library/web_browser.js

template_function: on
template_namespace: WebDoc.templates
templates:
  document_editor:
    - app/views/templates/test.html