development:
  s3_access_key_id: 'AKIAJSQQ2RDIXG2UOZ5Q'
  s3_secret_access_key: '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'
  assets:
    storage: file
  widgets:
    storage: file
test:
  s3_access_key_id: 'AKIAJSQQ2RDIXG2UOZ5Q'
  s3_secret_access_key: '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'
  assets:
    s3_bucket: 'assets.test.webdoc.com'
    storage: right_s3
  widgets:
    s3_bucket: 'apps.test.webdoc.com'
    storage: right_s3
staging:
  s3_access_key_id: 'AKIAJSQQ2RDIXG2UOZ5Q'
  s3_secret_access_key: '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'
  s3_bucket: "assets.staging.webdoc.com"
  storage: right_s3  
  assets:
    s3_bucket: "assets.staging.webdoc.com"
  widgets:
    s3_bucket: "apps.staging.webdoc.com"
production:
  s3_access_key_id: 'AKIAJSQQ2RDIXG2UOZ5Q'
  s3_secret_access_key: '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'
  storage: right_s3
  s3_bucket: "assets.webdoc.com"
  assets:
    s3_bucket: "assets.webdoc.com"
  widgets:
    s3_bucket: "apps.webdoc.com"
  