development:
  synch_openfire_users: false
  mail_from: dev@local
  notify_administrator_onuser_creation: true
  administrator_emails: julien@mnemis.com, stelio@mnemis.com, mathieu@mnemis.com, yann@mnemis.com  

test:
  synch_openfire_users: false

staging:
  synch_openfire_users: true
  openfire_user_service_url: http://localhost:9090/plugins/userService/
  openfire_user_service_secret: rt8BTv4C
  mail_from: st-wd@webdoc.com
  google_analytic_tracker_id: UA-11892994-2
  must_check_user_email: true

production:
  synch_openfire_users: true
  openfire_user_service_url: http://localhost:9090/plugins/userService/
  openfire_user_service_secret: pt2AFc2B
  google_analytic_tracker_id: UA-11892994-3
  notify_administrator_on_user_creation: true
  mail_from: info@webdoc.com
  must_check_user_email: true
  administrator_emails: julien.bachmann@mnemis.com, stelio.tzonis@mnemis.com, mathieu.fivaz@mnemis.com, yann.ringgenberg@mnemis.com
  