development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: webdoc_test
  username: webdoc
  password: webdoc
  host: localhost
  encoding: utf8
  collation: utf8_unicode_ci

staging:
  adapter: mysql2
  database: webdoc_staging
  username: webdoc
  password: webdoc
  host: localhost
  encoding: utf8
  collation: utf8_unicode_ci
  reconnect: true

production:
  adapter: mysql2
  database: webdoc_production
  username: webdoc
  password: webdoc
  host: localhost
  encoding: utf8
  collation: utf8_unicode_ci
  reconnect: true  
    
