development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: mysql
  database: webdoc_test
  username: webdoc
  password: webdoc
  host: localhost

staging:
  adapter: mysql
  database: webdoc_staging
  username: webdoc
  password: webdoc
  host: localhost

production:
  adapter: mysql
  database: webdoc_production
  username: webdoc
  password: webdoc
  host: webdoc-production.chnus0k5dbng.us-east-1.rds.amazonaws.com
