development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: mysql
  database: uniboard_test
  username: uniboard
  password: uniboard
  host: ub-db-mysql-staging

staging:
  adapter: mysql
  database: uniboard_staging
  username: uniboard
  password: uniboard
  host: localhost

production:
  adapter: mysql
  database: webdoc_production
  username: webdoc
  password: webdoc
  host: webdoc-db-master
