development:
  access_key_id: AKIAJSQQ2RDIXG2UOZ5Q
  secret_access_key: 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
  bucket: uniboard-development

test:
  access_key_id: AKIAJSQQ2RDIXG2UOZ5Q
  secret_access_key: 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
  bucket: uniboard-test

staging:
  access_key_id: AKIAJSQQ2RDIXG2UOZ5Q
  secret_access_key: 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
  bucket: uniboard-staging

production:
  access_key_id: AKIAJSQQ2RDIXG2UOZ5Q
  secret_access_key: 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
  bucket: uniboard
