development:
  access_key_id: AKIAJSQQ2RDIXG2UOZ5Q
  secret_access_key: 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

test:
  access_key_id: AKIAJSQQ2RDIXG2UOZ5Q
  secret_access_key: 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

staging:
  access_key_id: AKIAJSQQ2RDIXG2UOZ5Q
  secret_access_key: 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

production:
  access_key_id: AKIAJSQQ2RDIXG2UOZ5Q
  secret_access_key: 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
