common: &common
  access_key_id: 'XXXXXXXXXXXXXXXXXXXX'
  secret_access_key: 'XXXXXXXXXXXXXXXXXXXXXXXX'

development:
  <<: *common
  storage: filesystem
  assets_bucket: 'assets.test.webdoc.com'
  widgets_bucket: 'apps.test.webdoc.com'

test:
  <<: *common
  storage: s3
  assets_bucket: 'assets.test.webdoc.com'
  widgets_bucket: 'apps.test.webdoc.com'

staging:
  <<: *common
  storage: s3
  assets_bucket: 'assets.staging.webdoc.com'
  widgets_bucket: 'apps.staging.webdoc.com'

production:
  <<: *common
  storage: s3
  assets_bucket: 'assets.webdoc.com'
  widgets_bucket: 'apps.webdoc.com'
