development:
  aws_access_key: AKIAJSQQ2RDIXG2UOZ5Q
  aws_secret_access_key: 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
  bucket_base_name: uniboard-development-yann

test:
  aws_access_key:
  aws_secret_access_key:
  bucket_base_name: uniboard-test

staging:
  aws_access_key: AKIAJSQQ2RDIXG2UOZ5Q
  aws_secret_access_key: nYyZvtWLa3uDMmf8oEmSmyZiu7qmf
  bucket_base_name: uniboard-staging

production:
  aws_access_key: AKIAJSQQ2RDIXG2UOZ5Q
  aws_secret_access_key: nYyZvtWLa3uDMmf8oEmSmyZiu7qmf
  bucket_base_name: uniboard
